name: Update GitHub Stats to Output Branch

on:
  schedule:
    - cron: "0 12 1/5 * *"
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output folder
        run: mkdir -p dist

      - name: Download GitHub Stats
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://github-readme-stats.vercel.app/api?username=jln63&count_private=true&show_icons=true&hide_title=false&hide_rank=false&theme=prussian&locale=en&hide_border=false" \
            -o dist/github-stats.svg

      - name: Download GitHub Streak
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://streak-stats.demolab.com?user=jln63&locale=en&mode=daily&theme=prussian&hide_border=false&border_radius=5" \
            -o dist/github-streak.svg

      - name: Download Top Languages
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://github-readme-stats.vercel.app/api/top-langs?username=jln63&layout=compact&card_width=320&langs_count=5&theme=prussian&hide_border=false" \
            -o dist/github-langs.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
