# .github/workflows/update-stats.yml
name: Update GitHub Stats

on:
  schedule:
    - cron: "0 12 1/5 * *"  # Met à jour toutes les heures
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: anuraghazra/github-readme-stats@master
        with:
          USERNAME: jln63
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
