name: Update GitHub Stats to Output Branch

on:
  schedule:
    - cron: "0 12 1/5 * *"
  workflow_dispatch:

jobs:
  generate-stats:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Créer le dossier dist
        run: mkdir -p dist/{stats,streak,langs,snake}

      - name: Download GitHub Stats
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://github-readme-stats.vercel.app/api?username=jln63&count_private=true&show_icons=true&hide_title=false&hide_rank=false&theme=prussian&locale=en&hide_border=false" \
            -o dist/stats/github-stats.svg

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake/snake.svg?palette=github-dark

      - name: Download GitHub Streak
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://streak-stats.demolab.com?user=jln63&locale=en&mode=daily&theme=prussian&hide_border=false&border_radius=5" \
            -o dist/streak/github-streak.svg

      - name: Download Top Languages
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://github-readme-stats.vercel.app/api/top-langs?username=jln63&layout=compact&card_width=320&langs_count=5&theme=prussian&hide_border=false" \
            -o dist/langs/github-langs.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
