# .github/workflows/update-stats.yml
name: Update GitHub Stats

on:
  schedule:
    - cron: "0 12 1/5 * *"  # Met à jour toutes les heures
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Télécharger GitHub Stats (commits privés inclus)
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               "https://github-readme-stats.vercel.app/api?username=jln63&count_private=true&show_icons=true&hide_title=false&hide_rank=false&theme=prussian&locale=en&hide_border=false" \
               -o assets/github-stats.svg

      - name: Télécharger GitHub Streak
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               "https://streak-stats.demolab.com?user=jln63&locale=en&mode=daily&theme=prussian&hide_border=false&border_radius=5" \
               -o assets/github-streak.svg

      - name: Télécharger Top Langs
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               "https://github-readme-stats.vercel.app/api/top-langs?username=jln63&layout=compact&card_width=320&langs_count=5&theme=prussian&hide_border=false" \
               -o assets/github-langs.svg
               
      - name: Commit & push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add assets/github-*.svg
          git commit -m "update: GitHub stats images (auto)" || echo "No changes to commit"

      - name: Configure push avec GH_TOKEN
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}

      - name: Push les fichiers modifiés
        run: |
          git push origin HEAD
